### ISSUE TITLE
VisionWidget崩溃

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-UXSDK-Android#101]
```java
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'dji.common.mission.tapfly.TapFlyMode dji.internal.ddf.fdd.koy.ddd.uio()' on a null object reference
        at dji.sdk.mission.tapfly.TapFlyMissionOperator.getTapFlyMode(Unknown Source:2)
        at dji.ux.widget.VisionWidget.isVisionSystemEnabled(Unknown Source:14)
        at dji.ux.widget.VisionWidget.getSingleVisionSystemStatus(Unknown Source:4)
        at dji.ux.widget.VisionWidget.transformValue(Unknown Source:16)
        at dji.ux.base.n.a(Unknown Source:6)
        at dji.ux.base.n.call(Unknown Source:2)
        at dji.thirdparty.rx.internal.util.ScalarSynchronousObservable$4.call(ScalarSynchronousObservable.java:223)
        at dji.thirdparty.rx.internal.util.ScalarSynchronousObservable$4.call(ScalarSynchronousObservable.java:220)
```

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/40565'>Zendesk ticket #40565</a>:<br><br>Dear Client
Thank you for contacting DJI.

The visionWidget has been used in UXDEMO and it works, please have a look the demo.
Link：https://github.com/dji-sdk/Mobile-UXSDK-Android

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by dji-lisafedane** [comment]
Hi there - thanks for bringing this issue up but we need to know more about the context to be able to help.  Can you answer the following: 

1. Describe the issue - what results are you expecting and what are you getting instead?
2. What are the steps to recreate this behavior?
3. What drone are you using and what's it's firmware?
4. What Android device and OS version are you on?
5. What version of the UX SDK and MSDK are you using?
6.Please pass us the full crash log

Please note, that you can write your descriptions in Chinese if you need to and we will use our internal translators

**Comment by SJJ-dot** [comment]
> Hi there - thanks for bringing this issue up but we need to know more about the context to be able to help.  Can you answer the following: 
> 
> 1. Describe the issue - what results are you expecting and what are you getting instead?
> 2. What are the steps to recreate this behavior?
> 3. What drone are you using and what's it's firmware?
> 4. What Android device and OS version are you on?
> 5. What version of the UX SDK and MSDK are you using?
> 6.Please pass us the full crash log
> 
> Please note, that you can write your descriptions in Chinese if you need to and we will use our internal translators

p4p 最新版飞控固件。uxsdk最新版本。模拟器飞行。timeline航点任务结束时触发的崩溃。当时出现了3次以上。后来没再复现。日志:前面的堆栈信息还不够吗？至少希望你们能够规避崩溃。还有diji rxjava内部的全局异常为什么不拦截。目前我们应用崩溃的原因全部是来自dijisdk 和uxsdk。

**Comment by dji-lisafedane** [comment]
Translation: 

The latest version of p4p flight control firmware. 

The latest version of uxsdk. 

Simulator flight: A crash triggered at the end of a timeline waypoint mission. It appeared more than 3 times. It didn't reappear later. 

Log: Is the previous stack information not enough? At least I hope you can avoid the collapse. And why the global exception inside diji rxjava is not intercepted. At present, all the reasons for our application crash are from dijisdk and uxsdk.

**Comment by SJJ-dot** [comment]
```kotlin
class VisionWidget2(p0: Context?, p1: AttributeSet?) : VisionWidget(p0, p1) {

    override fun transformValueObservable(p0: Any?, p1: DJIKey?): Observable<Boolean> {
        return super.transformValueObservable(p0, p1).onErrorReturn { false }
    }
    override fun transformValue(p0: Any?, p1: DJIKey?) {
        try {
            return super.transformValue(p0, p1)
        } catch (e: Throwable) {
            Logger.e("${this.javaClass.simpleName} ${e.message}")
        }
    }
}
```
我处理了。再见
