### ISSUE TITLE
FPVWidget 怎么才能看到m300的相机画面呢？

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-UXSDK-Android#102]

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/40760'>Zendesk ticket #40760</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
需要使用assignSourceToPrimaryChannel分配下视频源，参考示例：
https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/camera/VideoFeederView.java

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
