### ISSUE TITLE
有现成的，和官方APP相同的rtk设置控件吗？

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-UXSDK-Android#103]
有现成的，和官方APP相同的rtk设置控件吗？

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/40899'>Zendesk ticket #40899</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

没有RTK设置控件，只有RTKStatusPanel。
Link：https://developer.dji.com/api-reference/android-uilib-api/Widgets/RTKStatusPanel.html

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
