### ISSUE TITLE
UXSDK Performances - Manifold issue

### ISSUE THREAD

**Issue by Caufmann** [dji-sdk/Mobile-UXSDK-Android#112]
Hi,

I am using M210V2, Manifold 2G, Crystal sky and UXSDK 4.13.

I am facing different issues : 
1/ Video Stream (Zenmuse x5s), using UXSDK, is freezing from time to time on the Crystal Sky
2/ I can't receive GPS Signal (GPSSignal Widget isn't updating even if I can see 7 satellites on the Remote Controller) using UXSDK
3/ When using UXSDK with Onboard SDK (on Manifold 2G), I can send and receive data, but receiving data make the application freeze.
4/ Video Stream (Zenmuse x5s) disappear from time to time when plugging Manifold using USB (even on the Pilot app)

My questions : 
 - Are these known issues  ?
 - Is the UXSDK supposed to work perfectly (Video Stream / Widgets / GPS / etc...)
 - Is it appropriate to use both Onboard SDK and UXSDK ?
 - I've read here (https://forum.dji.com/forum.php?mod=viewthread&tid=218852) that other people had this USB problem but I can't understand the solution, would you explain me this again please ?
 - Should I uninstall DJI Pilot on the Crystal Sky when running my custom app based on UXSDK ?

Thanks for your time,

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/43223'>Zendesk ticket #43223</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
1,3,4. That's so weird, please fill in the form to contact us again to investigate further in another thread.
https://formcrafts.com/a/dji-developer-feedback-en

2. Can you please test again with the latest 4.14trial1 version?
If the problem persists, please contact us via the below form.
https://github.com/dji-sdk/Mobile-UXSDK-Android


- Are these known issues ?
- -->No, need to investigate first.


- Is the UXSDK supposed to work perfectly (Video Stream / Widgets / GPS / etc...)

-->Yes, I tested with latest 4.14trial1 UXSDK sample, everything(Video Stream / Widgets / GPS / etc...) works well.



- Is it appropriate to use both Onboard SDK and UXSDK ?

-->Yes, it's possible to use both OSDK and UXSDK.



- I've read here (https://forum.dji.com/forum.php?mod=viewthread&tid=218852) that other people had this USB problem but I can't understand the solution, would you explain me this again please ?

-->In a USB mode, connect to the manifold2 via USB port(tail of the drone), the camera storage would treat as a SD card that it's normal, but the video stream will not be disappeared.



- Should I uninstall DJI Pilot on the Crystal Sky when running my custom app based on UXSDK ?

-->No, but please note that only one App(UXSDK or DJI Pilot) can work at a time.


Thanks,

Luce Luo
DJI Dev Team

**Comment by Caufmann** [comment]
Thank's a lot for your answer.

I fixed my problem with Manifold and USB thanks to you.

I'm still having issues with the FPV widget. I downloaded last UXSDK Versions and here are pictures of the issues :

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/43223'>Zendesk ticket #43223</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
I try to find an official UXSDK layout sample for you.
Please try to test if the problem persists or not.
https://github.com/dji-sdk/Mobile-UXSDK-Android/blob/master/sample/app/src/main/res/layout/activity_default_widgets.xml

If the problem persists, please fill in the form with more detail and we will investigate further on another thread.
https://formcrafts.com/a/dji-developer-feedback-en

Thanks,

Luce Luo
DJI Developer Support

**Comment by Caufmann** [comment]
Hi,

Sorry for the late response.

I'll close this issue and investigate further.

Thank you for your support
