### ISSUE TITLE
DJI SDK Waypoint Mission - UploadMission error

### ISSUE THREAD

**Issue by laboBea** [dji-sdk/Mobile-UXSDK-Android#124]
I'm developing an Android Application that uses the DJI UXSDK. The drone I'm using right now is the Mavic Pro 1. This application wants to use the predefined classes for waypoints inside the DJI SDK to create missions for the drone, but when performing the configuration of the Waypoint mission and correctly loading the mission inisde the Mission Operator (current state is set to: READY_TO_UPLOAD after calling the MissionOperator.loadMission), when trying to perform the "uploadMission" predefined function the app crashes and the Drone automatically disconects of the Application.

I think the waypoints are correctly created and saved inside the builder, otherwise it would fail in the loadMission function. Also the parameters are correct since the checkParameters function is used.

If anyone has the correct steps to setup Waypoint missions or knows the error it would be of great help for all the DJI UXSDK users.

The function that fails is the follwing one: 

```
private void uploadWayPointMission(){
getWaypointMissionOperator().uploadMission(new CommonCallbacks.CompletionCallback() {
    @Override
   public void onResult(DJIError error) {
        if (error == null) {
            setResultToToast("Mission upload successfully!");
        } else {
            setResultToToast("Mission upload failed, error: " + error.getDescription());
        } 
    }
});
}
```
It is in concret the line: `getWaypointMissionOperator().uploadMission(new CommonCallbacks.CompletionCallback() {` that is causing the crash. It does not even get to the override of the OnResult beforfe crashing.

The state of the Mission Operator is checked before calling this function and it is "READY_TO_UPLOAD" so I don't know where can be failing.

Tried to surround it with try/catch but it does not work anyway, the view of the map in which I am designing the mission close and the Mavic pro is automatically disconnected from the android device I'm using to control it and I need to reset the app to regain the connection with the drone.

Could it be because of FlySafe? I am doing the mission inside an "Authorization Zone" (blue color in DJI GEO Zone), my drone has the athorization to fly in this type of area and if I want, I can fly it manually without problems, also the state of the drone is "Ready to fly" so it shouldn't be a problem but maybe the Waypoint mission don't allow it?

To create the mission I create two waypoints by clicking in the map (as before two you are not allowed to loadMission) and everything is fine until the upload of the mission inside the Mission Operator.

Best regards, Thanks in advance

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/47313'>Zendesk ticket #47313</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
I'm not sure the problem.
Can you please post the crash log?

Also, here is an official the sample, please try to refer and test it.
https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/missionoperator/WaypointMissionOperatorView.java

Thanks,

Luce Luo
DJI Developer Support<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/47313'>Zendesk ticket #47313</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
In general, the crash log was in the mobile device folder, DJI->\PROJECT\->LOG->CRASH.
And the mission needs to transplant to the UXSDK project by yourself.

Thanks,

Luce Luo
DJI Developer Support
<br><p><em><small>°°°</small></em></p>

**Comment by laboBea** [comment]
Hello,

The issue was solved and the Waypoint mission works normally.
The problem (in case someone is in the same situation) was that when uploading the misson it tried to plot a Toast at screen that crashed the application. The problem was not the uploadMission itself.
Solved by simply inputing:
                    runOnUiThread {
                    }
And the Toasts inside the brackets. Now it works fine.

Best regards,
