### ISSUE TITLE
点击...出现的面板设置，ux有提供这样的设置组件么

### ISSUE THREAD

**Issue by Swordce** [dji-sdk/Mobile-UXSDK-Android#125]
![微信图片_20210514161825](https://user-images.githubusercontent.com/16829238/118242714-33315380-b4d0-11eb-902f-535f0dc966e9.jpg)

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/47687'>Zendesk ticket #47687</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
抱歉，UXSDK中没有您图示中的组件，所有组件如下：
https://developer.dji.com/api-reference/android-uilib-api/Widgets/DULFPVWidget.html

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
