### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by RenzoBeux** [dji-sdk/Mobile-UXSDK-Android#127]
Hi! Wanted to know if localization is or will ever be avaliable. Thank you!

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/48124'>Zendesk ticket #48124</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
The UXSDK doesn't support localization, please use the open-source version.
https://github.com/dji-sdk/Mobile-UXSDK-Beta-Android

Thanks,

Luce Luo
DJI Developer Support
<br><p><em><small>°°°</small></em></p>
