### ISSUE TITLE
最新版：dji.ux.widget.PreFlightStatusWidget 子线程加载xml 报错。如果在xml 前面加上 dji.ux.widget.FPVOverlayWidget 就正常，这是为什么？

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-UXSDK-Android#129]

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/49345'>Zendesk ticket #49345</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
理论上两者没有联系，您可以直接测试下官方UXSDKsample，去掉对比试试。
https://github.com/dji-sdk/Mobile-UXSDK-Android

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
