### ISSUE TITLE
Read H20 radar at high frequency

### ISSUE THREAD

**Issue by GregCornis** [dji-sdk/Mobile-UXSDK-Android#153]
Hi,
I'm wondering if we can have access to the laser distances measured by the H20 at a high frequency ?
We're currently reading it via `CameraKey.KeyLaserMeasureInformation`, but the reading is only 5Hz, and we're looking for at least 20Hz.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/111995'>Zendesk ticket #111995</a>:<br><br>Why is such a high frequency needed?

The measurement data frequency of the camera may not be able to reach 20Hz.
<br><p><em><small>°°°</small></em></p>

**Comment by GregCornis** [comment]
We're looking to detect an object passing in front of the drone pretty quickly, and wondering whether the laser can detect that

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/111995'>Zendesk ticket #111995</a>:<br><br>Greetings!
I have just confirmed that the frequency of CameraKey.KeyLaserMeasureInformation is controlled by the drone protocol. Sorry, but currently the SDK cannot increase its frequency.
<br><p><em><small>°°°</small></em></p>

**Comment by GregCornis** [comment]
Ok thanks

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/111995'>Zendesk ticket #111995</a>:<br><br>I hope everything goes smoothly for you.
<br><p><em><small>°°°</small></em></p>
