### ISSUE TITLE
UX的菜单控件的文字设置为中文

### ISSUE THREAD

**Issue by 15201884835** [dji-sdk/Mobile-UXSDK-Android#47]
如何设置那些菜单面板的文字信息为中文？

**Comment by userZhaolei** [comment]
同问，你解决了吗？

**Comment by Ly-lijiawei** [comment]
同问，你解决了吗？

**Comment by dji-dev** [comment]
DJI在近期发布了Android UXSDK Beta版本：[https://github.com/dji-sdk/Mobile-UXSDK-Beta-Android](https://github.com/dji-sdk/Mobile-UXSDK-Beta-Android)， 所有的strings 都被提取出来放到资源文件中，您可以自己做本地化翻译了。

请问您的问题是否已解决，如果仍有疑问，请填写以下表单：[https://formcrafts.com/a/dji-developer-feedback-cn](https://formcrafts.com/a/dji-developer-feedback-cn) 反馈给我们，或者发送邮件到dev@dji.com. 感谢您的理解和配合。
