### ISSUE TITLE
BatteryWidget 组件不显示

### ISSUE THREAD

**Issue by MRYangY** [dji-sdk/Mobile-UXSDK-Android#54]
父容器是constraintlayout，关于BatteryWidget的xml代码如下：

**Comment by MRYangY** [comment]
<dji.ux.widget.BatteryWidget
        android:id="@+id/dji_drone_battery"
        android:layout_width="50dp"
        android:layout_height="50dp"
        custom:excludeView="singleVoltage|doubleVoltage"
        custom:layout_constraintBottom_toBottomOf="parent"
        custom:layout_constraintLeft_toRightOf="@+id/dji_drone_gpssignal"
        custom:layout_constraintTop_toBottomOf="@+id/dji_pre_flight_status">

    </dji.ux.widget.BatteryWidget>

**Comment by MRYangY** [comment]
连接dji飞行器后，battery组件会闪现一下（位置是不对的），然后又不见了

**Comment by dji-dev** [comment]
> Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/26451'>Zendesk ticket #26451</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
您可以参考一下UXSDK官方示例中的布局和使用方式：
https://github.com/dji-sdk/Mobile-UXSDK-Android/blob/master/sample/app/src/main/res/layout/activity_customized_widgets.xml

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by MRYangY** [comment]
使用LinearLayout线性布局的话，没问题，如果用相对布局和约束布局就会出现问题。

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/26451'>Zendesk ticket #26451</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
抱歉，与工程师确认了。为了兼容所有的小部件能够正常运行，UXSDK布局方面是特别定制的，
对于UXSDK小部件建议您使用线性布局而不要使用其他布局。

如果有特殊需要，建议您可以使用MSDK自行重构一个类似组件。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
