### ISSUE TITLE
FPV Widget with DJI LightBridge

### ISSUE THREAD

**Issue by gitnarqt** [dji-sdk/Mobile-UXSDK-Android#55]
Hello,
In the sample app, DJI is using VideoFeederView, a custom class, to show the feed of the DJI drone. I've tried doing something similar with the FPVWidget with no luck. I've set EXT to single-mode and put LB to 100% and am still getting no feed. Is there something I missed here?

**Comment by dji-dev** [comment]
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/27074'>Zendesk ticket #27074</a>:<br><br>Can you tell me what drone and cameras you are using?  Also, please specify your camera configuration if you are using a dual gimbal (ie. port vs. starboard side)

Lisa Fedane
DJI Developer Support

**Comment by gitnarqt** [comment]
Hello Lisa,
Thank you for reverting back!

We're using a DJI M600, Ronin MX, with a Sony camera.

**Comment by dji-lisafedane** [comment]
@gitnarqt - A few questions: 
1. Have you tried your set up with a different camera or connected directly into your computer? 
2. Which Sony camera is it?
3. Does this video capture how you've set up your system? https://www.youtube.com/watch?v=xJeo2EZmtS0 Are there any differences?

**Comment by dji-dev** [comment]
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/27074'>Zendesk ticket #27074</a>:<br><br>@gitnarqt - A few questions:

1. Have you tried your set up with a different camera or connected directly into your computer?
2. Which Sony camera is it?
3. Does this video capture how you've set up your system? https://www.youtube.com/watch?v=xJeo2EZmtS0 Are there any differences?


Lisa Fedane
DJI Developer Support

**Comment by gitnarqt** [comment]
@dji-dev Lisa, thank you for getting back to me! The issue has been solved. We had to set the camera to primary after performing all these steps. Thank you so much again.
