### ISSUE TITLE
duplicate value for resource 'attr/textSize' with config 

### ISSUE THREAD

**Issue by yubaorong** [dji-sdk/Mobile-UXSDK-Android#57]
uxsdk中textSize属性和android v7包中的textSize冲突
![image](https://user-images.githubusercontent.com/27795757/64088021-0e379400-cd72-11e9-8ad7-2009efb69ae5.png)

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/27646'>Zendesk ticket #27646</a>:<br><br>尊敬的用户，

您好！感谢您联系DJI 大疆创新。
为了快速收集问题细节，麻烦您详细填写如下表格。
https://formcrafts.com/a/dji-developer-feedback-cn

在收到您的详细细节信息后，我们将会进行快速处理。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
