### ISSUE TITLE
Google play issue. How to remove amap sdk? 

### ISSUE THREAD

**Issue by Chickinnick** [dji-sdk/Mobile-UXSDK-Android#64]
An app distributed via Google Play may not modify, replace, or update itself using any method other than Google Play's update mechanism. Likewise, an app may not download executable code (e.g. dex, JAR, .so files) from a source other than Google Play.

We found that your app is using a non-compliant version of the AMAP SDK which contains code to download executable code (e.g. dex, JAR, .so files) from a source other than Google Play. If necessary, you can consult your SDK provider(s) for further information.

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/30776'>Zendesk ticket #30776</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Please refer to the following setting:
implementation ('com.dji:dji-uxsdk:4.11',
{ exclude group: 'com.amap.api' }
)

Thanks,

DJI Dev Team
