### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by gsrathoreniks** [dji-sdk/Mobile-UXSDK-Android#66]
In the description, "iOS" should be replaced by "Android"

<img width="1057" alt="Screenshot 2020-02-28 at 1 44 34 PM" src="https://user-images.githubusercontent.com/19241334/75522669-8be21100-5a30-11ea-9259-407bfc8d32ae.png">

Not a bit issue, but a change would be better!

**Comment by dji-dev** [comment]
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/32459'>Zendesk ticket #32459</a>:<br><br>Thanks for bringing this to our attention!  We'll get this fixed soon.

Lisa Fedane
DJI Developer Support

**Comment by gsrathoreniks** [comment]
cool

**Comment by dji-dev** [comment]
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/32459'>Zendesk ticket #32459</a>:<br><br>The documentation is fixed - please continue to let us know if you catch things like this.

Thanks!

Lisa Fedane
DJI Developer Support
