### ISSUE TITLE
使用UXSDK后, 推流一会儿就自动断开

### ISSUE THREAD

**Issue by addriumruss** [dji-sdk/Mobile-UXSDK-Android#73]
![2 png](https://user-images.githubusercontent.com/35988105/80188520-e15b2880-8643-11ea-8cbb-7f67d522aad8.jpg)

如上图。 有时候1分钟，有时候5分钟就自动断开. 
飞机是御2pro, 用go 4手机app只观看不会断。
uxsdk和djsdk都是4.11.2。
请问这是为什么?

**Comment by addriumruss** [comment]
右上角显示红色"飞行器未连接"，左上角黑屏“UNKNOWN”

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/33905'>Zendesk ticket #33905</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

您尝试跑一下Sample App中的直播功能看看有没有相同的问题出现，或者用DJI PILOT去直播一下看看，DJI PILOT也是由MSDK开发而来。有可能是UXSDK DEMO的BUG。
https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/camera/LiveStreamView.java

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
