### ISSUE TITLE
Error inflating class dji.ux.widget.FPVWidget

### ISSUE THREAD

**Issue by wuyan12138** [dji-sdk/Mobile-UXSDK-Android#80]
I have integrated the DJI UXSDK 4.12 into my Android Project following this [tutorial](https://developer.dji.com/cn/mobile-sdk/documentation/application-development-workflow/workflow-integrate.html), then I tried to transit  [those code](https://github.com/DJI-Mobile-SDK-Tutorials/Android-UXSDKDemo)  to my project, however ,every time when it runs to `setContentView(R.layout.activity_patrol_page);` (id activity_patrol_page is the same as activity_main.xml [here](https://github.com/DJI-Mobile-SDK-Tutorials/Android-UXSDKDemo/tree/master/UXSDKDemo/app/src/main/res/layout)), such error occcures,`Error inflating class dji.ux.widget.FPVWidget`,and then my app was killed,I tried in my Android X mobilephone and an Android 7.0 AVD, both failed.I have no progress at here for 3 days and Googled a lot, and haven't find a solution yet.But It is strange that if I build and run the [demo](https://github.com/DJI-Mobile-SDK-Tutorials/Android-UXSDKDemo) seperatly,it can run correctly.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/35487'>Zendesk ticket #35487</a>:<br><br>Dear Client
Thank you for contacting DJI.

Then it must be something wrong with your code in your project. Personally I feel like it is something wrong in layout configuration. Pay more attention to your xml file. And also compare your code to the demo for every function that you need to implemetnation.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by wuyan12138** [comment]
@dji-dev thanks a lot, but the xml file comes from the DJI UXSDK Demo and I did not change it.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/35487'>Zendesk ticket #35487</a>:<br><br>Dear Client
Thank you for contacting DJI.

For your own project, if the project name/settings change, sometimes the xml is also required to be changed.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by wuyan12138** [comment]
I have solved this problem by checking my xml file and MApplication file again. Thanks a lot.@dji-dev

**Comment by Viokeoke** [comment]
Hello, I have the same issue and I have checked the code comparing it with the demo (The demo applications work as expected), but I did not find any solution. How did you solve it?

**Comment by Viokeoke** [comment]
I have solved the issue, I had a custom style that did not have a parent from Theme.AppCompat.Light
