### ISSUE TITLE
How to get Bitmap from DJI FPVWeight?

### ISSUE THREAD

**Issue by ziji-wu** [dji-sdk/Mobile-UXSDK-Android#82]
Now I have a problem that I do not know how to get a Bitmap from fpvweight, Is there any wany can I do this?

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/36780'>Zendesk ticket #36780</a>:<br><br>Dear Client
Thank you for contacting DJI.

please refer to the link below, it contains how you get bitmap from downloading preview photos. The process will be, use the camera capture a photo from FPV view. Then download the photo preview and store it into bitmap format.
Link：https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/camera/FetchMediaView.java

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
