### ISSUE TITLE
Failed to resolve: com.dji:dji-uxsdk:4.13.1 Show in Project Structure dialog Affected Modules: app

### ISSUE THREAD

**Issue by zongoalbert** [dji-sdk/Mobile-UXSDK-Android#93]
when i open the project with android studio : its give me this error :
```
Failed to resolve: com.dji:dji-uxsdk:4.13.1
Show in Project Structure dialog
Affected Modules: app
```

**Comment by alainpimentel** [comment]
@zongoalbert there is no 4.13.1 version of UX SDK. However, you should be able to update MSDK to 4.13.1.
We will update the sample build.gradle with an example soon.

**Comment by alainpimentel** [comment]
@zongoalbert the README file of this repo was updated to show how to add MSDK 4.13.1.
